//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("RentACarModel", "FK_Kategori_KategoriResim", "Kategori", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RentACar.Veritabani.Entity.Kategori), "KategoriResim", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RentACar.Veritabani.Entity.KategoriResim), true)]
[assembly: EdmRelationshipAttribute("RentACarModel", "FK_Kategori_KategoriTanim", "Kategori", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RentACar.Veritabani.Entity.Kategori), "KategoriTanim", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RentACar.Veritabani.Entity.KategoriTanim), true)]
[assembly: EdmRelationshipAttribute("RentACarModel", "FK_Urun_Kategori", "Kategori", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RentACar.Veritabani.Entity.Kategori), "Urun", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RentACar.Veritabani.Entity.Urun), true)]
[assembly: EdmRelationshipAttribute("RentACarModel", "FK_Urun_UrunTanim", "Urun", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RentACar.Veritabani.Entity.Urun), "UrunTanim", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RentACar.Veritabani.Entity.UrunTanim), true)]
[assembly: EdmRelationshipAttribute("RentACarModel", "FK_UrunFiyat_Urun", "Urun", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RentACar.Veritabani.Entity.Urun), "UrunFiyat", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RentACar.Veritabani.Entity.UrunFiyat), true)]
[assembly: EdmRelationshipAttribute("RentACarModel", "FK_Urun_UrunResim", "Urun", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RentACar.Veritabani.Entity.Urun), "UrunResim", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RentACar.Veritabani.Entity.UrunResim), true)]

#endregion

namespace RentACar.Veritabani.Entity
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class RentACarEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new RentACarEntities object using the connection string found in the 'RentACarEntities' section of the application configuration file.
        /// </summary>
        public RentACarEntities()
            : base("metadata=res://*/Entity.RentACarModel.csdl|res://*/Entity.RentACarModel.ssdl|res://*/Entity.RentACarModel.msl;provider=System.Data.SqlClient;provider connection string='Data Source=.;Initial Catalog=RentACar;Integrated Security=True;MultipleActiveResultSets=True'", "RentACarEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RentACarEntities object.
        /// </summary>
        public RentACarEntities(string connectionString) : base(connectionString, "RentACarEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RentACarEntities object.
        /// </summary>
        public RentACarEntities(EntityConnection connection) : base(connection, "RentACarEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<KategoriResim> KategoriResim
        {
            get
            {
                if ((_KategoriResim == null))
                {
                    _KategoriResim = base.CreateObjectSet<KategoriResim>("KategoriResim");
                }
                return _KategoriResim;
            }
        }
        private ObjectSet<KategoriResim> _KategoriResim;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<KategoriTanim> KategoriTanim
        {
            get
            {
                if ((_KategoriTanim == null))
                {
                    _KategoriTanim = base.CreateObjectSet<KategoriTanim>("KategoriTanim");
                }
                return _KategoriTanim;
            }
        }
        private ObjectSet<KategoriTanim> _KategoriTanim;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UrunTanim> UrunTanim
        {
            get
            {
                if ((_UrunTanim == null))
                {
                    _UrunTanim = base.CreateObjectSet<UrunTanim>("UrunTanim");
                }
                return _UrunTanim;
            }
        }
        private ObjectSet<UrunTanim> _UrunTanim;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Kategori> Kategori
        {
            get
            {
                if ((_Kategori == null))
                {
                    _Kategori = base.CreateObjectSet<Kategori>("Kategori");
                }
                return _Kategori;
            }
        }
        private ObjectSet<Kategori> _Kategori;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UrunFiyat> UrunFiyat
        {
            get
            {
                if ((_UrunFiyat == null))
                {
                    _UrunFiyat = base.CreateObjectSet<UrunFiyat>("UrunFiyat");
                }
                return _UrunFiyat;
            }
        }
        private ObjectSet<UrunFiyat> _UrunFiyat;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Urun> Urun
        {
            get
            {
                if ((_Urun == null))
                {
                    _Urun = base.CreateObjectSet<Urun>("Urun");
                }
                return _Urun;
            }
        }
        private ObjectSet<Urun> _Urun;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UrunResim> UrunResim
        {
            get
            {
                if ((_UrunResim == null))
                {
                    _UrunResim = base.CreateObjectSet<UrunResim>("UrunResim");
                }
                return _UrunResim;
            }
        }
        private ObjectSet<UrunResim> _UrunResim;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the KategoriResim EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKategoriResim(KategoriResim kategoriResim)
        {
            base.AddObject("KategoriResim", kategoriResim);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the KategoriTanim EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKategoriTanim(KategoriTanim kategoriTanim)
        {
            base.AddObject("KategoriTanim", kategoriTanim);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UrunTanim EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUrunTanim(UrunTanim urunTanim)
        {
            base.AddObject("UrunTanim", urunTanim);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Kategori EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKategori(Kategori kategori)
        {
            base.AddObject("Kategori", kategori);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UrunFiyat EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUrunFiyat(UrunFiyat urunFiyat)
        {
            base.AddObject("UrunFiyat", urunFiyat);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Urun EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUrun(Urun urun)
        {
            base.AddObject("Urun", urun);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UrunResim EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUrunResim(UrunResim urunResim)
        {
            base.AddObject("UrunResim", urunResim);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RentACarModel", Name="Kategori")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Kategori : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Kategori object.
        /// </summary>
        /// <param name="kategoriId">Initial value of the KategoriId property.</param>
        /// <param name="sil">Initial value of the Sil property.</param>
        /// <param name="kategoriAd">Initial value of the KategoriAd property.</param>
        public static Kategori CreateKategori(global::System.Int32 kategoriId, global::System.Int32 sil, global::System.String kategoriAd)
        {
            Kategori kategori = new Kategori();
            kategori.KategoriId = kategoriId;
            kategori.Sil = sil;
            kategori.KategoriAd = kategoriAd;
            return kategori;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 KategoriId
        {
            get
            {
                return _KategoriId;
            }
            set
            {
                if (_KategoriId != value)
                {
                    OnKategoriIdChanging(value);
                    ReportPropertyChanging("KategoriId");
                    _KategoriId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("KategoriId");
                    OnKategoriIdChanged();
                }
            }
        }
        private global::System.Int32 _KategoriId;
        partial void OnKategoriIdChanging(global::System.Int32 value);
        partial void OnKategoriIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Sil
        {
            get
            {
                return _Sil;
            }
            set
            {
                OnSilChanging(value);
                ReportPropertyChanging("Sil");
                _Sil = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sil");
                OnSilChanged();
            }
        }
        private global::System.Int32 _Sil;
        partial void OnSilChanging(global::System.Int32 value);
        partial void OnSilChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String KategoriAd
        {
            get
            {
                return _KategoriAd;
            }
            set
            {
                OnKategoriAdChanging(value);
                ReportPropertyChanging("KategoriAd");
                _KategoriAd = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("KategoriAd");
                OnKategoriAdChanged();
            }
        }
        private global::System.String _KategoriAd;
        partial void OnKategoriAdChanging(global::System.String value);
        partial void OnKategoriAdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RentACarModel", "FK_Kategori_KategoriResim", "KategoriResim")]
        public EntityCollection<KategoriResim> KategoriResim
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<KategoriResim>("RentACarModel.FK_Kategori_KategoriResim", "KategoriResim");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<KategoriResim>("RentACarModel.FK_Kategori_KategoriResim", "KategoriResim", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RentACarModel", "FK_Kategori_KategoriTanim", "KategoriTanim")]
        public EntityCollection<KategoriTanim> KategoriTanim
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<KategoriTanim>("RentACarModel.FK_Kategori_KategoriTanim", "KategoriTanim");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<KategoriTanim>("RentACarModel.FK_Kategori_KategoriTanim", "KategoriTanim", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RentACarModel", "FK_Urun_Kategori", "Urun")]
        public EntityCollection<Urun> Urun
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Urun>("RentACarModel.FK_Urun_Kategori", "Urun");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Urun>("RentACarModel.FK_Urun_Kategori", "Urun", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RentACarModel", Name="KategoriResim")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class KategoriResim : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new KategoriResim object.
        /// </summary>
        /// <param name="kategoriResimId">Initial value of the KategoriResimId property.</param>
        /// <param name="kategoriId">Initial value of the KategoriId property.</param>
        /// <param name="resimPath">Initial value of the ResimPath property.</param>
        /// <param name="anaResimMi">Initial value of the AnaResimMi property.</param>
        public static KategoriResim CreateKategoriResim(global::System.Int32 kategoriResimId, global::System.Int32 kategoriId, global::System.String resimPath, global::System.Boolean anaResimMi)
        {
            KategoriResim kategoriResim = new KategoriResim();
            kategoriResim.KategoriResimId = kategoriResimId;
            kategoriResim.KategoriId = kategoriId;
            kategoriResim.ResimPath = resimPath;
            kategoriResim.AnaResimMi = anaResimMi;
            return kategoriResim;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 KategoriResimId
        {
            get
            {
                return _KategoriResimId;
            }
            set
            {
                if (_KategoriResimId != value)
                {
                    OnKategoriResimIdChanging(value);
                    ReportPropertyChanging("KategoriResimId");
                    _KategoriResimId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("KategoriResimId");
                    OnKategoriResimIdChanged();
                }
            }
        }
        private global::System.Int32 _KategoriResimId;
        partial void OnKategoriResimIdChanging(global::System.Int32 value);
        partial void OnKategoriResimIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 KategoriId
        {
            get
            {
                return _KategoriId;
            }
            set
            {
                OnKategoriIdChanging(value);
                ReportPropertyChanging("KategoriId");
                _KategoriId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KategoriId");
                OnKategoriIdChanged();
            }
        }
        private global::System.Int32 _KategoriId;
        partial void OnKategoriIdChanging(global::System.Int32 value);
        partial void OnKategoriIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ResimPath
        {
            get
            {
                return _ResimPath;
            }
            set
            {
                OnResimPathChanging(value);
                ReportPropertyChanging("ResimPath");
                _ResimPath = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ResimPath");
                OnResimPathChanged();
            }
        }
        private global::System.String _ResimPath;
        partial void OnResimPathChanging(global::System.String value);
        partial void OnResimPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean AnaResimMi
        {
            get
            {
                return _AnaResimMi;
            }
            set
            {
                OnAnaResimMiChanging(value);
                ReportPropertyChanging("AnaResimMi");
                _AnaResimMi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AnaResimMi");
                OnAnaResimMiChanged();
            }
        }
        private global::System.Boolean _AnaResimMi;
        partial void OnAnaResimMiChanging(global::System.Boolean value);
        partial void OnAnaResimMiChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RentACarModel", "FK_Kategori_KategoriResim", "Kategori")]
        public Kategori Kategori
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kategori>("RentACarModel.FK_Kategori_KategoriResim", "Kategori").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kategori>("RentACarModel.FK_Kategori_KategoriResim", "Kategori").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Kategori> KategoriReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kategori>("RentACarModel.FK_Kategori_KategoriResim", "Kategori");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Kategori>("RentACarModel.FK_Kategori_KategoriResim", "Kategori", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RentACarModel", Name="KategoriTanim")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class KategoriTanim : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new KategoriTanim object.
        /// </summary>
        /// <param name="kategoriTanimId">Initial value of the KategoriTanimId property.</param>
        /// <param name="kategoriId">Initial value of the KategoriId property.</param>
        /// <param name="ad">Initial value of the Ad property.</param>
        public static KategoriTanim CreateKategoriTanim(global::System.Int32 kategoriTanimId, global::System.Int32 kategoriId, global::System.String ad)
        {
            KategoriTanim kategoriTanim = new KategoriTanim();
            kategoriTanim.KategoriTanimId = kategoriTanimId;
            kategoriTanim.KategoriId = kategoriId;
            kategoriTanim.Ad = ad;
            return kategoriTanim;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 KategoriTanimId
        {
            get
            {
                return _KategoriTanimId;
            }
            set
            {
                if (_KategoriTanimId != value)
                {
                    OnKategoriTanimIdChanging(value);
                    ReportPropertyChanging("KategoriTanimId");
                    _KategoriTanimId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("KategoriTanimId");
                    OnKategoriTanimIdChanged();
                }
            }
        }
        private global::System.Int32 _KategoriTanimId;
        partial void OnKategoriTanimIdChanging(global::System.Int32 value);
        partial void OnKategoriTanimIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 KategoriId
        {
            get
            {
                return _KategoriId;
            }
            set
            {
                OnKategoriIdChanging(value);
                ReportPropertyChanging("KategoriId");
                _KategoriId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KategoriId");
                OnKategoriIdChanged();
            }
        }
        private global::System.Int32 _KategoriId;
        partial void OnKategoriIdChanging(global::System.Int32 value);
        partial void OnKategoriIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Aciklama
        {
            get
            {
                return _Aciklama;
            }
            set
            {
                OnAciklamaChanging(value);
                ReportPropertyChanging("Aciklama");
                _Aciklama = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Aciklama");
                OnAciklamaChanged();
            }
        }
        private global::System.String _Aciklama;
        partial void OnAciklamaChanging(global::System.String value);
        partial void OnAciklamaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ad
        {
            get
            {
                return _Ad;
            }
            set
            {
                OnAdChanging(value);
                ReportPropertyChanging("Ad");
                _Ad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Ad");
                OnAdChanged();
            }
        }
        private global::System.String _Ad;
        partial void OnAdChanging(global::System.String value);
        partial void OnAdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DilTip
        {
            get
            {
                return _DilTip;
            }
            set
            {
                OnDilTipChanging(value);
                ReportPropertyChanging("DilTip");
                _DilTip = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DilTip");
                OnDilTipChanged();
            }
        }
        private Nullable<global::System.Int32> _DilTip;
        partial void OnDilTipChanging(Nullable<global::System.Int32> value);
        partial void OnDilTipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ozet
        {
            get
            {
                return _Ozet;
            }
            set
            {
                OnOzetChanging(value);
                ReportPropertyChanging("Ozet");
                _Ozet = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ozet");
                OnOzetChanged();
            }
        }
        private global::System.String _Ozet;
        partial void OnOzetChanging(global::System.String value);
        partial void OnOzetChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RentACarModel", "FK_Kategori_KategoriTanim", "Kategori")]
        public Kategori Kategori
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kategori>("RentACarModel.FK_Kategori_KategoriTanim", "Kategori").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kategori>("RentACarModel.FK_Kategori_KategoriTanim", "Kategori").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Kategori> KategoriReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kategori>("RentACarModel.FK_Kategori_KategoriTanim", "Kategori");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Kategori>("RentACarModel.FK_Kategori_KategoriTanim", "Kategori", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RentACarModel", Name="Urun")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Urun : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Urun object.
        /// </summary>
        /// <param name="urunId">Initial value of the UrunId property.</param>
        /// <param name="kategoriId">Initial value of the KategoriId property.</param>
        /// <param name="sil">Initial value of the Sil property.</param>
        /// <param name="urunAd">Initial value of the UrunAd property.</param>
        public static Urun CreateUrun(global::System.Int32 urunId, global::System.Int32 kategoriId, global::System.Int32 sil, global::System.String urunAd)
        {
            Urun urun = new Urun();
            urun.UrunId = urunId;
            urun.KategoriId = kategoriId;
            urun.Sil = sil;
            urun.UrunAd = urunAd;
            return urun;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UrunId
        {
            get
            {
                return _UrunId;
            }
            set
            {
                if (_UrunId != value)
                {
                    OnUrunIdChanging(value);
                    ReportPropertyChanging("UrunId");
                    _UrunId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UrunId");
                    OnUrunIdChanged();
                }
            }
        }
        private global::System.Int32 _UrunId;
        partial void OnUrunIdChanging(global::System.Int32 value);
        partial void OnUrunIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 KategoriId
        {
            get
            {
                return _KategoriId;
            }
            set
            {
                OnKategoriIdChanging(value);
                ReportPropertyChanging("KategoriId");
                _KategoriId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KategoriId");
                OnKategoriIdChanged();
            }
        }
        private global::System.Int32 _KategoriId;
        partial void OnKategoriIdChanging(global::System.Int32 value);
        partial void OnKategoriIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Sil
        {
            get
            {
                return _Sil;
            }
            set
            {
                OnSilChanging(value);
                ReportPropertyChanging("Sil");
                _Sil = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sil");
                OnSilChanged();
            }
        }
        private global::System.Int32 _Sil;
        partial void OnSilChanging(global::System.Int32 value);
        partial void OnSilChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UrunAd
        {
            get
            {
                return _UrunAd;
            }
            set
            {
                OnUrunAdChanging(value);
                ReportPropertyChanging("UrunAd");
                _UrunAd = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UrunAd");
                OnUrunAdChanged();
            }
        }
        private global::System.String _UrunAd;
        partial void OnUrunAdChanging(global::System.String value);
        partial void OnUrunAdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Aciklama
        {
            get
            {
                return _Aciklama;
            }
            set
            {
                OnAciklamaChanging(value);
                ReportPropertyChanging("Aciklama");
                _Aciklama = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Aciklama");
                OnAciklamaChanged();
            }
        }
        private global::System.String _Aciklama;
        partial void OnAciklamaChanging(global::System.String value);
        partial void OnAciklamaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RentACarModel", "FK_Urun_Kategori", "Kategori")]
        public Kategori Kategori
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kategori>("RentACarModel.FK_Urun_Kategori", "Kategori").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kategori>("RentACarModel.FK_Urun_Kategori", "Kategori").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Kategori> KategoriReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kategori>("RentACarModel.FK_Urun_Kategori", "Kategori");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Kategori>("RentACarModel.FK_Urun_Kategori", "Kategori", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RentACarModel", "FK_Urun_UrunTanim", "UrunTanim")]
        public EntityCollection<UrunTanim> UrunTanim
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UrunTanim>("RentACarModel.FK_Urun_UrunTanim", "UrunTanim");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UrunTanim>("RentACarModel.FK_Urun_UrunTanim", "UrunTanim", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RentACarModel", "FK_UrunFiyat_Urun", "UrunFiyat")]
        public EntityCollection<UrunFiyat> UrunFiyat
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UrunFiyat>("RentACarModel.FK_UrunFiyat_Urun", "UrunFiyat");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UrunFiyat>("RentACarModel.FK_UrunFiyat_Urun", "UrunFiyat", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RentACarModel", "FK_Urun_UrunResim", "UrunResim")]
        public EntityCollection<UrunResim> UrunResim
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UrunResim>("RentACarModel.FK_Urun_UrunResim", "UrunResim");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UrunResim>("RentACarModel.FK_Urun_UrunResim", "UrunResim", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RentACarModel", Name="UrunFiyat")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UrunFiyat : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UrunFiyat object.
        /// </summary>
        /// <param name="urunFiyatId">Initial value of the UrunFiyatId property.</param>
        /// <param name="urunFiyatTip">Initial value of the UrunFiyatTip property.</param>
        /// <param name="urunId">Initial value of the UrunId property.</param>
        /// <param name="fiyat">Initial value of the Fiyat property.</param>
        public static UrunFiyat CreateUrunFiyat(global::System.Int32 urunFiyatId, global::System.Int32 urunFiyatTip, global::System.Int32 urunId, global::System.Decimal fiyat)
        {
            UrunFiyat urunFiyat = new UrunFiyat();
            urunFiyat.UrunFiyatId = urunFiyatId;
            urunFiyat.UrunFiyatTip = urunFiyatTip;
            urunFiyat.UrunId = urunId;
            urunFiyat.Fiyat = fiyat;
            return urunFiyat;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UrunFiyatId
        {
            get
            {
                return _UrunFiyatId;
            }
            set
            {
                if (_UrunFiyatId != value)
                {
                    OnUrunFiyatIdChanging(value);
                    ReportPropertyChanging("UrunFiyatId");
                    _UrunFiyatId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UrunFiyatId");
                    OnUrunFiyatIdChanged();
                }
            }
        }
        private global::System.Int32 _UrunFiyatId;
        partial void OnUrunFiyatIdChanging(global::System.Int32 value);
        partial void OnUrunFiyatIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UrunFiyatTip
        {
            get
            {
                return _UrunFiyatTip;
            }
            set
            {
                OnUrunFiyatTipChanging(value);
                ReportPropertyChanging("UrunFiyatTip");
                _UrunFiyatTip = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UrunFiyatTip");
                OnUrunFiyatTipChanged();
            }
        }
        private global::System.Int32 _UrunFiyatTip;
        partial void OnUrunFiyatTipChanging(global::System.Int32 value);
        partial void OnUrunFiyatTipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UrunId
        {
            get
            {
                return _UrunId;
            }
            set
            {
                OnUrunIdChanging(value);
                ReportPropertyChanging("UrunId");
                _UrunId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UrunId");
                OnUrunIdChanged();
            }
        }
        private global::System.Int32 _UrunId;
        partial void OnUrunIdChanging(global::System.Int32 value);
        partial void OnUrunIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Fiyat
        {
            get
            {
                return _Fiyat;
            }
            set
            {
                OnFiyatChanging(value);
                ReportPropertyChanging("Fiyat");
                _Fiyat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fiyat");
                OnFiyatChanged();
            }
        }
        private global::System.Decimal _Fiyat;
        partial void OnFiyatChanging(global::System.Decimal value);
        partial void OnFiyatChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RentACarModel", "FK_UrunFiyat_Urun", "Urun")]
        public Urun Urun
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Urun>("RentACarModel.FK_UrunFiyat_Urun", "Urun").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Urun>("RentACarModel.FK_UrunFiyat_Urun", "Urun").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Urun> UrunReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Urun>("RentACarModel.FK_UrunFiyat_Urun", "Urun");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Urun>("RentACarModel.FK_UrunFiyat_Urun", "Urun", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RentACarModel", Name="UrunResim")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UrunResim : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UrunResim object.
        /// </summary>
        /// <param name="urunResimId">Initial value of the UrunResimId property.</param>
        /// <param name="resimPath">Initial value of the ResimPath property.</param>
        /// <param name="urunId">Initial value of the UrunId property.</param>
        /// <param name="anaResimMi">Initial value of the AnaResimMi property.</param>
        public static UrunResim CreateUrunResim(global::System.Int32 urunResimId, global::System.String resimPath, global::System.Int32 urunId, global::System.Boolean anaResimMi)
        {
            UrunResim urunResim = new UrunResim();
            urunResim.UrunResimId = urunResimId;
            urunResim.ResimPath = resimPath;
            urunResim.UrunId = urunId;
            urunResim.AnaResimMi = anaResimMi;
            return urunResim;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UrunResimId
        {
            get
            {
                return _UrunResimId;
            }
            set
            {
                if (_UrunResimId != value)
                {
                    OnUrunResimIdChanging(value);
                    ReportPropertyChanging("UrunResimId");
                    _UrunResimId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UrunResimId");
                    OnUrunResimIdChanged();
                }
            }
        }
        private global::System.Int32 _UrunResimId;
        partial void OnUrunResimIdChanging(global::System.Int32 value);
        partial void OnUrunResimIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ResimPath
        {
            get
            {
                return _ResimPath;
            }
            set
            {
                OnResimPathChanging(value);
                ReportPropertyChanging("ResimPath");
                _ResimPath = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ResimPath");
                OnResimPathChanged();
            }
        }
        private global::System.String _ResimPath;
        partial void OnResimPathChanging(global::System.String value);
        partial void OnResimPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UrunId
        {
            get
            {
                return _UrunId;
            }
            set
            {
                OnUrunIdChanging(value);
                ReportPropertyChanging("UrunId");
                _UrunId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UrunId");
                OnUrunIdChanged();
            }
        }
        private global::System.Int32 _UrunId;
        partial void OnUrunIdChanging(global::System.Int32 value);
        partial void OnUrunIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean AnaResimMi
        {
            get
            {
                return _AnaResimMi;
            }
            set
            {
                OnAnaResimMiChanging(value);
                ReportPropertyChanging("AnaResimMi");
                _AnaResimMi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AnaResimMi");
                OnAnaResimMiChanged();
            }
        }
        private global::System.Boolean _AnaResimMi;
        partial void OnAnaResimMiChanging(global::System.Boolean value);
        partial void OnAnaResimMiChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RentACarModel", "FK_Urun_UrunResim", "Urun")]
        public Urun Urun
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Urun>("RentACarModel.FK_Urun_UrunResim", "Urun").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Urun>("RentACarModel.FK_Urun_UrunResim", "Urun").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Urun> UrunReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Urun>("RentACarModel.FK_Urun_UrunResim", "Urun");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Urun>("RentACarModel.FK_Urun_UrunResim", "Urun", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RentACarModel", Name="UrunTanim")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UrunTanim : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UrunTanim object.
        /// </summary>
        /// <param name="urunTanimId">Initial value of the UrunTanimId property.</param>
        /// <param name="aciklama">Initial value of the Aciklama property.</param>
        /// <param name="ad">Initial value of the Ad property.</param>
        /// <param name="ozet">Initial value of the Ozet property.</param>
        /// <param name="urunId">Initial value of the UrunId property.</param>
        /// <param name="dilTip">Initial value of the DilTip property.</param>
        public static UrunTanim CreateUrunTanim(global::System.Int32 urunTanimId, global::System.String aciklama, global::System.String ad, global::System.String ozet, global::System.Int32 urunId, global::System.Int32 dilTip)
        {
            UrunTanim urunTanim = new UrunTanim();
            urunTanim.UrunTanimId = urunTanimId;
            urunTanim.Aciklama = aciklama;
            urunTanim.Ad = ad;
            urunTanim.Ozet = ozet;
            urunTanim.UrunId = urunId;
            urunTanim.DilTip = dilTip;
            return urunTanim;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UrunTanimId
        {
            get
            {
                return _UrunTanimId;
            }
            set
            {
                if (_UrunTanimId != value)
                {
                    OnUrunTanimIdChanging(value);
                    ReportPropertyChanging("UrunTanimId");
                    _UrunTanimId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UrunTanimId");
                    OnUrunTanimIdChanged();
                }
            }
        }
        private global::System.Int32 _UrunTanimId;
        partial void OnUrunTanimIdChanging(global::System.Int32 value);
        partial void OnUrunTanimIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Aciklama
        {
            get
            {
                return _Aciklama;
            }
            set
            {
                OnAciklamaChanging(value);
                ReportPropertyChanging("Aciklama");
                _Aciklama = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Aciklama");
                OnAciklamaChanged();
            }
        }
        private global::System.String _Aciklama;
        partial void OnAciklamaChanging(global::System.String value);
        partial void OnAciklamaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ad
        {
            get
            {
                return _Ad;
            }
            set
            {
                OnAdChanging(value);
                ReportPropertyChanging("Ad");
                _Ad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Ad");
                OnAdChanged();
            }
        }
        private global::System.String _Ad;
        partial void OnAdChanging(global::System.String value);
        partial void OnAdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ozet
        {
            get
            {
                return _Ozet;
            }
            set
            {
                OnOzetChanging(value);
                ReportPropertyChanging("Ozet");
                _Ozet = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Ozet");
                OnOzetChanged();
            }
        }
        private global::System.String _Ozet;
        partial void OnOzetChanging(global::System.String value);
        partial void OnOzetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UrunId
        {
            get
            {
                return _UrunId;
            }
            set
            {
                OnUrunIdChanging(value);
                ReportPropertyChanging("UrunId");
                _UrunId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UrunId");
                OnUrunIdChanged();
            }
        }
        private global::System.Int32 _UrunId;
        partial void OnUrunIdChanging(global::System.Int32 value);
        partial void OnUrunIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DilTip
        {
            get
            {
                return _DilTip;
            }
            set
            {
                OnDilTipChanging(value);
                ReportPropertyChanging("DilTip");
                _DilTip = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DilTip");
                OnDilTipChanged();
            }
        }
        private global::System.Int32 _DilTip;
        partial void OnDilTipChanging(global::System.Int32 value);
        partial void OnDilTipChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RentACarModel", "FK_Urun_UrunTanim", "Urun")]
        public Urun Urun
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Urun>("RentACarModel.FK_Urun_UrunTanim", "Urun").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Urun>("RentACarModel.FK_Urun_UrunTanim", "Urun").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Urun> UrunReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Urun>("RentACarModel.FK_Urun_UrunTanim", "Urun");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Urun>("RentACarModel.FK_Urun_UrunTanim", "Urun", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
