//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("rentacar1Model", "Kategori_KategoriResim", "kategori", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RentACar.Veritabani.TestEntity.kategori), "kategoriresim", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RentACar.Veritabani.TestEntity.kategoriresim), true)]
[assembly: EdmRelationshipAttribute("rentacar1Model", "Kategori_KategoriTanim", "kategori", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RentACar.Veritabani.TestEntity.kategori), "kategoritanim", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RentACar.Veritabani.TestEntity.kategoritanim), true)]
[assembly: EdmRelationshipAttribute("rentacar1Model", "Urun_UrunResim", "urun", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RentACar.Veritabani.TestEntity.urun), "urunresim", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RentACar.Veritabani.TestEntity.urunresim), true)]
[assembly: EdmRelationshipAttribute("rentacar1Model", "Urun_UrunTanim", "urun", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(RentACar.Veritabani.TestEntity.urun), "uruntanim", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RentACar.Veritabani.TestEntity.uruntanim), true)]

#endregion

namespace RentACar.Veritabani.TestEntity
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class rentacar1EntitiesWeb : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new rentacar1EntitiesWeb object using the connection string found in the 'rentacar1EntitiesWeb' section of the application configuration file.
        /// </summary>
        public rentacar1EntitiesWeb() : base("name=rentacar1EntitiesWeb", "rentacar1EntitiesWeb")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new rentacar1EntitiesWeb object.
        /// </summary>
        public rentacar1EntitiesWeb(string connectionString) : base(connectionString, "rentacar1EntitiesWeb")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new rentacar1EntitiesWeb object.
        /// </summary>
        public rentacar1EntitiesWeb(EntityConnection connection) : base(connection, "rentacar1EntitiesWeb")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<kategori> kategori
        {
            get
            {
                if ((_kategori == null))
                {
                    _kategori = base.CreateObjectSet<kategori>("kategori");
                }
                return _kategori;
            }
        }
        private ObjectSet<kategori> _kategori;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<kategoriresim> kategoriresim
        {
            get
            {
                if ((_kategoriresim == null))
                {
                    _kategoriresim = base.CreateObjectSet<kategoriresim>("kategoriresim");
                }
                return _kategoriresim;
            }
        }
        private ObjectSet<kategoriresim> _kategoriresim;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<kategoritanim> kategoritanim
        {
            get
            {
                if ((_kategoritanim == null))
                {
                    _kategoritanim = base.CreateObjectSet<kategoritanim>("kategoritanim");
                }
                return _kategoritanim;
            }
        }
        private ObjectSet<kategoritanim> _kategoritanim;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<urun> urun
        {
            get
            {
                if ((_urun == null))
                {
                    _urun = base.CreateObjectSet<urun>("urun");
                }
                return _urun;
            }
        }
        private ObjectSet<urun> _urun;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<urunresim> urunresim
        {
            get
            {
                if ((_urunresim == null))
                {
                    _urunresim = base.CreateObjectSet<urunresim>("urunresim");
                }
                return _urunresim;
            }
        }
        private ObjectSet<urunresim> _urunresim;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<uruntanim> uruntanim
        {
            get
            {
                if ((_uruntanim == null))
                {
                    _uruntanim = base.CreateObjectSet<uruntanim>("uruntanim");
                }
                return _uruntanim;
            }
        }
        private ObjectSet<uruntanim> _uruntanim;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the kategori EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTokategori(kategori kategori)
        {
            base.AddObject("kategori", kategori);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the kategoriresim EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTokategoriresim(kategoriresim kategoriresim)
        {
            base.AddObject("kategoriresim", kategoriresim);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the kategoritanim EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTokategoritanim(kategoritanim kategoritanim)
        {
            base.AddObject("kategoritanim", kategoritanim);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the urun EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTourun(urun urun)
        {
            base.AddObject("urun", urun);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the urunresim EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTourunresim(urunresim urunresim)
        {
            base.AddObject("urunresim", urunresim);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the uruntanim EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTouruntanim(uruntanim uruntanim)
        {
            base.AddObject("uruntanim", uruntanim);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="rentacar1Model", Name="kategori")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class kategori : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new kategori object.
        /// </summary>
        /// <param name="kategoriId">Initial value of the KategoriId property.</param>
        /// <param name="sil">Initial value of the Sil property.</param>
        public static kategori Createkategori(global::System.Int32 kategoriId, global::System.Int32 sil)
        {
            kategori kategori = new kategori();
            kategori.KategoriId = kategoriId;
            kategori.Sil = sil;
            return kategori;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KategoriAd
        {
            get
            {
                return _KategoriAd;
            }
            set
            {
                OnKategoriAdChanging(value);
                ReportPropertyChanging("KategoriAd");
                _KategoriAd = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KategoriAd");
                OnKategoriAdChanged();
            }
        }
        private global::System.String _KategoriAd;
        partial void OnKategoriAdChanging(global::System.String value);
        partial void OnKategoriAdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 KategoriId
        {
            get
            {
                return _KategoriId;
            }
            set
            {
                if (_KategoriId != value)
                {
                    OnKategoriIdChanging(value);
                    ReportPropertyChanging("KategoriId");
                    _KategoriId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("KategoriId");
                    OnKategoriIdChanged();
                }
            }
        }
        private global::System.Int32 _KategoriId;
        partial void OnKategoriIdChanging(global::System.Int32 value);
        partial void OnKategoriIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Sil
        {
            get
            {
                return _Sil;
            }
            set
            {
                OnSilChanging(value);
                ReportPropertyChanging("Sil");
                _Sil = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sil");
                OnSilChanged();
            }
        }
        private global::System.Int32 _Sil;
        partial void OnSilChanging(global::System.Int32 value);
        partial void OnSilChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("rentacar1Model", "Kategori_KategoriResim", "kategoriresim")]
        public EntityCollection<kategoriresim> kategoriresim
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<kategoriresim>("rentacar1Model.Kategori_KategoriResim", "kategoriresim");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<kategoriresim>("rentacar1Model.Kategori_KategoriResim", "kategoriresim", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("rentacar1Model", "Kategori_KategoriTanim", "kategoritanim")]
        public EntityCollection<kategoritanim> kategoritanim
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<kategoritanim>("rentacar1Model.Kategori_KategoriTanim", "kategoritanim");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<kategoritanim>("rentacar1Model.Kategori_KategoriTanim", "kategoritanim", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="rentacar1Model", Name="kategoriresim")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class kategoriresim : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new kategoriresim object.
        /// </summary>
        /// <param name="kategoriId">Initial value of the KategoriId property.</param>
        /// <param name="kategoriResimId">Initial value of the KategoriResimId property.</param>
        public static kategoriresim Createkategoriresim(global::System.Int32 kategoriId, global::System.Int32 kategoriResimId)
        {
            kategoriresim kategoriresim = new kategoriresim();
            kategoriresim.KategoriId = kategoriId;
            kategoriresim.KategoriResimId = kategoriResimId;
            return kategoriresim;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 KategoriId
        {
            get
            {
                return _KategoriId;
            }
            set
            {
                OnKategoriIdChanging(value);
                ReportPropertyChanging("KategoriId");
                _KategoriId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KategoriId");
                OnKategoriIdChanged();
            }
        }
        private global::System.Int32 _KategoriId;
        partial void OnKategoriIdChanging(global::System.Int32 value);
        partial void OnKategoriIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 KategoriResimId
        {
            get
            {
                return _KategoriResimId;
            }
            set
            {
                if (_KategoriResimId != value)
                {
                    OnKategoriResimIdChanging(value);
                    ReportPropertyChanging("KategoriResimId");
                    _KategoriResimId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("KategoriResimId");
                    OnKategoriResimIdChanged();
                }
            }
        }
        private global::System.Int32 _KategoriResimId;
        partial void OnKategoriResimIdChanging(global::System.Int32 value);
        partial void OnKategoriResimIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ResimPath
        {
            get
            {
                return _ResimPath;
            }
            set
            {
                OnResimPathChanging(value);
                ReportPropertyChanging("ResimPath");
                _ResimPath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ResimPath");
                OnResimPathChanged();
            }
        }
        private global::System.String _ResimPath;
        partial void OnResimPathChanging(global::System.String value);
        partial void OnResimPathChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("rentacar1Model", "Kategori_KategoriResim", "kategori")]
        public kategori kategori
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<kategori>("rentacar1Model.Kategori_KategoriResim", "kategori").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<kategori>("rentacar1Model.Kategori_KategoriResim", "kategori").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<kategori> kategoriReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<kategori>("rentacar1Model.Kategori_KategoriResim", "kategori");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<kategori>("rentacar1Model.Kategori_KategoriResim", "kategori", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="rentacar1Model", Name="kategoritanim")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class kategoritanim : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new kategoritanim object.
        /// </summary>
        /// <param name="ad">Initial value of the Ad property.</param>
        /// <param name="kategoriId">Initial value of the KategoriId property.</param>
        /// <param name="kategoriTanimId">Initial value of the KategoriTanimId property.</param>
        public static kategoritanim Createkategoritanim(global::System.String ad, global::System.Int32 kategoriId, global::System.Int32 kategoriTanimId)
        {
            kategoritanim kategoritanim = new kategoritanim();
            kategoritanim.Ad = ad;
            kategoritanim.KategoriId = kategoriId;
            kategoritanim.KategoriTanimId = kategoriTanimId;
            return kategoritanim;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Aciklama
        {
            get
            {
                return _Aciklama;
            }
            set
            {
                OnAciklamaChanging(value);
                ReportPropertyChanging("Aciklama");
                _Aciklama = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Aciklama");
                OnAciklamaChanged();
            }
        }
        private global::System.String _Aciklama;
        partial void OnAciklamaChanging(global::System.String value);
        partial void OnAciklamaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ad
        {
            get
            {
                return _Ad;
            }
            set
            {
                OnAdChanging(value);
                ReportPropertyChanging("Ad");
                _Ad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Ad");
                OnAdChanged();
            }
        }
        private global::System.String _Ad;
        partial void OnAdChanging(global::System.String value);
        partial void OnAdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DilTip
        {
            get
            {
                return _DilTip;
            }
            set
            {
                OnDilTipChanging(value);
                ReportPropertyChanging("DilTip");
                _DilTip = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DilTip");
                OnDilTipChanged();
            }
        }
        private Nullable<global::System.Int32> _DilTip;
        partial void OnDilTipChanging(Nullable<global::System.Int32> value);
        partial void OnDilTipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 KategoriId
        {
            get
            {
                return _KategoriId;
            }
            set
            {
                OnKategoriIdChanging(value);
                ReportPropertyChanging("KategoriId");
                _KategoriId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KategoriId");
                OnKategoriIdChanged();
            }
        }
        private global::System.Int32 _KategoriId;
        partial void OnKategoriIdChanging(global::System.Int32 value);
        partial void OnKategoriIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 KategoriTanimId
        {
            get
            {
                return _KategoriTanimId;
            }
            set
            {
                if (_KategoriTanimId != value)
                {
                    OnKategoriTanimIdChanging(value);
                    ReportPropertyChanging("KategoriTanimId");
                    _KategoriTanimId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("KategoriTanimId");
                    OnKategoriTanimIdChanged();
                }
            }
        }
        private global::System.Int32 _KategoriTanimId;
        partial void OnKategoriTanimIdChanging(global::System.Int32 value);
        partial void OnKategoriTanimIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ozet
        {
            get
            {
                return _Ozet;
            }
            set
            {
                OnOzetChanging(value);
                ReportPropertyChanging("Ozet");
                _Ozet = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ozet");
                OnOzetChanged();
            }
        }
        private global::System.String _Ozet;
        partial void OnOzetChanging(global::System.String value);
        partial void OnOzetChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("rentacar1Model", "Kategori_KategoriTanim", "kategori")]
        public kategori kategori
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<kategori>("rentacar1Model.Kategori_KategoriTanim", "kategori").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<kategori>("rentacar1Model.Kategori_KategoriTanim", "kategori").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<kategori> kategoriReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<kategori>("rentacar1Model.Kategori_KategoriTanim", "kategori");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<kategori>("rentacar1Model.Kategori_KategoriTanim", "kategori", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="rentacar1Model", Name="urun")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class urun : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new urun object.
        /// </summary>
        /// <param name="kategoriId">Initial value of the KategoriId property.</param>
        /// <param name="sil">Initial value of the Sil property.</param>
        /// <param name="urunId">Initial value of the UrunId property.</param>
        public static urun Createurun(global::System.Int32 kategoriId, global::System.Int32 sil, global::System.Int32 urunId)
        {
            urun urun = new urun();
            urun.KategoriId = kategoriId;
            urun.Sil = sil;
            urun.UrunId = urunId;
            return urun;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 KategoriId
        {
            get
            {
                return _KategoriId;
            }
            set
            {
                OnKategoriIdChanging(value);
                ReportPropertyChanging("KategoriId");
                _KategoriId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KategoriId");
                OnKategoriIdChanged();
            }
        }
        private global::System.Int32 _KategoriId;
        partial void OnKategoriIdChanging(global::System.Int32 value);
        partial void OnKategoriIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Sil
        {
            get
            {
                return _Sil;
            }
            set
            {
                OnSilChanging(value);
                ReportPropertyChanging("Sil");
                _Sil = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sil");
                OnSilChanged();
            }
        }
        private global::System.Int32 _Sil;
        partial void OnSilChanging(global::System.Int32 value);
        partial void OnSilChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UrunId
        {
            get
            {
                return _UrunId;
            }
            set
            {
                if (_UrunId != value)
                {
                    OnUrunIdChanging(value);
                    ReportPropertyChanging("UrunId");
                    _UrunId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UrunId");
                    OnUrunIdChanged();
                }
            }
        }
        private global::System.Int32 _UrunId;
        partial void OnUrunIdChanging(global::System.Int32 value);
        partial void OnUrunIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("rentacar1Model", "Urun_UrunResim", "urunresim")]
        public EntityCollection<urunresim> urunresim
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<urunresim>("rentacar1Model.Urun_UrunResim", "urunresim");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<urunresim>("rentacar1Model.Urun_UrunResim", "urunresim", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("rentacar1Model", "Urun_UrunTanim", "uruntanim")]
        public EntityCollection<uruntanim> uruntanim
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<uruntanim>("rentacar1Model.Urun_UrunTanim", "uruntanim");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<uruntanim>("rentacar1Model.Urun_UrunTanim", "uruntanim", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="rentacar1Model", Name="urunresim")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class urunresim : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new urunresim object.
        /// </summary>
        /// <param name="urunId">Initial value of the UrunId property.</param>
        /// <param name="urunResimId">Initial value of the UrunResimId property.</param>
        public static urunresim Createurunresim(global::System.Int32 urunId, global::System.Int32 urunResimId)
        {
            urunresim urunresim = new urunresim();
            urunresim.UrunId = urunId;
            urunresim.UrunResimId = urunResimId;
            return urunresim;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ResimPath
        {
            get
            {
                return _ResimPath;
            }
            set
            {
                OnResimPathChanging(value);
                ReportPropertyChanging("ResimPath");
                _ResimPath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ResimPath");
                OnResimPathChanged();
            }
        }
        private global::System.String _ResimPath;
        partial void OnResimPathChanging(global::System.String value);
        partial void OnResimPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UrunId
        {
            get
            {
                return _UrunId;
            }
            set
            {
                OnUrunIdChanging(value);
                ReportPropertyChanging("UrunId");
                _UrunId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UrunId");
                OnUrunIdChanged();
            }
        }
        private global::System.Int32 _UrunId;
        partial void OnUrunIdChanging(global::System.Int32 value);
        partial void OnUrunIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UrunResimId
        {
            get
            {
                return _UrunResimId;
            }
            set
            {
                if (_UrunResimId != value)
                {
                    OnUrunResimIdChanging(value);
                    ReportPropertyChanging("UrunResimId");
                    _UrunResimId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UrunResimId");
                    OnUrunResimIdChanged();
                }
            }
        }
        private global::System.Int32 _UrunResimId;
        partial void OnUrunResimIdChanging(global::System.Int32 value);
        partial void OnUrunResimIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("rentacar1Model", "Urun_UrunResim", "urun")]
        public urun urun
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<urun>("rentacar1Model.Urun_UrunResim", "urun").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<urun>("rentacar1Model.Urun_UrunResim", "urun").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<urun> urunReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<urun>("rentacar1Model.Urun_UrunResim", "urun");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<urun>("rentacar1Model.Urun_UrunResim", "urun", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="rentacar1Model", Name="uruntanim")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class uruntanim : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new uruntanim object.
        /// </summary>
        /// <param name="urunId">Initial value of the UrunId property.</param>
        /// <param name="urunTanimId">Initial value of the UrunTanimId property.</param>
        public static uruntanim Createuruntanim(global::System.Int32 urunId, global::System.Int32 urunTanimId)
        {
            uruntanim uruntanim = new uruntanim();
            uruntanim.UrunId = urunId;
            uruntanim.UrunTanimId = urunTanimId;
            return uruntanim;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Aciklama
        {
            get
            {
                return _Aciklama;
            }
            set
            {
                OnAciklamaChanging(value);
                ReportPropertyChanging("Aciklama");
                _Aciklama = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Aciklama");
                OnAciklamaChanged();
            }
        }
        private global::System.String _Aciklama;
        partial void OnAciklamaChanging(global::System.String value);
        partial void OnAciklamaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ad
        {
            get
            {
                return _Ad;
            }
            set
            {
                OnAdChanging(value);
                ReportPropertyChanging("Ad");
                _Ad = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ad");
                OnAdChanged();
            }
        }
        private global::System.String _Ad;
        partial void OnAdChanging(global::System.String value);
        partial void OnAdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DilTip
        {
            get
            {
                return _DilTip;
            }
            set
            {
                OnDilTipChanging(value);
                ReportPropertyChanging("DilTip");
                _DilTip = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DilTip");
                OnDilTipChanged();
            }
        }
        private Nullable<global::System.Int32> _DilTip;
        partial void OnDilTipChanging(Nullable<global::System.Int32> value);
        partial void OnDilTipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ozet
        {
            get
            {
                return _Ozet;
            }
            set
            {
                OnOzetChanging(value);
                ReportPropertyChanging("Ozet");
                _Ozet = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ozet");
                OnOzetChanged();
            }
        }
        private global::System.String _Ozet;
        partial void OnOzetChanging(global::System.String value);
        partial void OnOzetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UrunId
        {
            get
            {
                return _UrunId;
            }
            set
            {
                OnUrunIdChanging(value);
                ReportPropertyChanging("UrunId");
                _UrunId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UrunId");
                OnUrunIdChanged();
            }
        }
        private global::System.Int32 _UrunId;
        partial void OnUrunIdChanging(global::System.Int32 value);
        partial void OnUrunIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UrunTanimId
        {
            get
            {
                return _UrunTanimId;
            }
            set
            {
                if (_UrunTanimId != value)
                {
                    OnUrunTanimIdChanging(value);
                    ReportPropertyChanging("UrunTanimId");
                    _UrunTanimId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UrunTanimId");
                    OnUrunTanimIdChanged();
                }
            }
        }
        private global::System.Int32 _UrunTanimId;
        partial void OnUrunTanimIdChanging(global::System.Int32 value);
        partial void OnUrunTanimIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("rentacar1Model", "Urun_UrunTanim", "urun")]
        public urun urun
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<urun>("rentacar1Model.Urun_UrunTanim", "urun").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<urun>("rentacar1Model.Urun_UrunTanim", "urun").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<urun> urunReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<urun>("rentacar1Model.Urun_UrunTanim", "urun");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<urun>("rentacar1Model.Urun_UrunTanim", "urun", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
